spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #	初始化时建立物理连接的个数
      initial-size: 1
      # 最大连接池数量
      max-active: 20
      # 最小连接池数量
      min-idle: 3
      # 获取连接时最大等待时间，单位毫秒
      max-wait: 60000
      # MySql、PostgreSQL校验
      validation-query: select 1
      # Oracle校验
      #validation-query: select 1 from dual
      #	单位：秒，检测连接是否有效的超时时间
      validation-query-timeout: 2000
      # Destroy线程会检测连接的间隔时间
      time-between-eviction-runs-millis: 60000
      # 连接保持空闲而不被驱逐的最长时间
      min-evictable-idle-time-millis: 300000
      # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      test-on-borrow: false
      # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      test-on-return: false
      # 建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效
      test-while-idle: true
      # 是否缓存preparedStatement
      pool-prepared-statements: false
      # 要启用PSCache，必须配置大于0
      # max-pool-prepared-statement-per-connection-size: 20

##xml扫描路径
#mybatis-plus:
#  mapper-locations: classpath*:/com/_54year/dawn/**/*Mapper.xml,classpath*:/mapper/*Mapper.xml
#
##日志相关配置
#logging:
#  level:
#    root: info
#    org:
#      springframework:
#        web: debug
#


dawn:
  redis:
    #基础连接信息配置 单机与多节点
    #是否使用集群 true为集群连接模式 false为单机连接
    useNodes: false
    #单节点配置
    hostName: 127.0.0.1
    port: 6379
    #集群节点配置
    nodes:
      - 127.0.0.1:6379
    #异常时最大重试次数 集群连接时会使用该配置
    maxAttempts: 5
    #密码
    password:

    # 连接池配置
    # 连接超时时间
    timeout: 10000
    #最大空闲数
    maxIdle: 299
    #控制一个pool可分配多少个jedis实例,用来替换上面的redis.maxActive,如果是jedis 2.4以后用该属性
    maxTotal: 1000
    #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
    maxWaitMillis: 1000
    #连接的最小空闲时间 默认1800000毫秒(30分钟)
    minEvictableIdleTimeMillis: 300000
    #每次释放连接的最大数目,默认3
    numTestsPerEvictionRun: 1024
    #逐出扫描的时间间隔(毫秒) 如果为负数,则不运行逐出线程, 默认-1
    timeBetweenEvictionRunsMillis: 30000
    #是否在从池中取出连接前进行检验,如果检验失败,则从池中去除连接并尝试取出另一个
    testOnBorrow: true
    #在空闲时检查有效性, 默认false
    testWhileIdle: true


